services:
  mongodb:
    image: mongo:7
    container_name: ai-book-reader-mongodb
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 8

  python-backend:
    build:
      context: .
      dockerfile: python-backend/Dockerfile
    image: ashfaq357/keeb-paython-backend:latest
    container_name: ai-book-reader-python
    env_file:
      - .env
    volumes:
      - ./python-backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ashfaq357/ai-auth-backend:latest
    container_name: ai-book-reader-backend
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy
      python-backend:
        condition: service_started

volumes:
  mongo_data:

networks:
  default:
    name: shared-proxy-net
    external: true
